version: '3.7'
services:
  blogdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./blog-db:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - proxy-net
networks:
  proxy-net:
    name: fantasyblog_blog-db-network