version: '3.1'
services:
  blog-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - "./blog-db:/var/lib/postgresql/data"
    ports:
    - 5434:5432