version: '3.8'
services:
  springapp:
    build:
      context: ..
      dockerfile: ./Dockerfile-alternate
    container_name: blog-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://blogdb:5432/blog
    ports:
      - 8000:8080
    networks:
      - default
networks:
  default:
    external:
      name: fantasyblog_blog-db-network